-- Inleggeld, aanmelder details and payment status for wedstrijd registrations.

-- ---------------------------------------------------------------- inleggeld
--
-- Stored in cents, not euros. Money in a floating-point column eventually produces a
-- total that is a cent out and cannot be explained to a penningmeester.
--
-- NULL means gratis. A separate boolean would allow the contradictory state
-- "gratis = false with no amount set", so absence carries the meaning instead.
alter table public.tournaments
  add column if not exists inleggeld_cents integer
    check (inleggeld_cents is null or inleggeld_cents >= 0);

comment on column public.tournaments.inleggeld_cents is
  'Inleggeld in centen. NULL betekent gratis.';

-- Online payment is only meaningful when there is something to pay.
alter table public.tournaments
  add column if not exists betaling_verplicht boolean not null default false;

-- ---------------------------------------------------------------- aanmelder
--
-- The person submitting the registration, who is not necessarily one of the players —
-- often a parent or a partuur captain. Their contact details belong to the registration,
-- not to any player_profiles row.
alter table public.tournament_registrations
  add column if not exists aanmelder_naam text,
  add column if not exists aanmelder_email text,
  add column if not exists aanmelder_telefoon text;

-- ---------------------------------------------------------------- betaling
--
-- Five states, matching what a club actually needs to distinguish. 'pending' exists
-- because a payment provider can take minutes to confirm, and during that window the
-- registration is neither unpaid nor paid — treating it as either one is what produces
-- double charges and lost registrations.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'betaalstatus') then
    create type public.betaalstatus as enum (
      'unpaid',    -- Nog niet betaald
      'pending',   -- Betaling in behandeling
      'paid',      -- Betaald
      'failed',    -- Betaling mislukt
      'refunded'   -- Terugbetaald
    );
  end if;
end $$;

alter table public.tournament_registrations
  add column if not exists betaalstatus public.betaalstatus not null default 'unpaid',
  add column if not exists betaald_cents integer check (betaald_cents is null or betaald_cents >= 0),
  add column if not exists betaald_op timestamptz,
  -- The provider's own identifier, so a webhook can find this row again.
  add column if not exists betaling_referentie text,
  -- Set when a beheerder confirms, or automatically once payment succeeds.
  add column if not exists bevestigd_op timestamptz;

-- One provider reference maps to exactly one registration. This is what stops a replayed
-- webhook or a double return from the payment page being processed twice.
create unique index if not exists tournament_registrations_betaling_referentie_key
  on public.tournament_registrations (betaling_referentie)
  where betaling_referentie is not null;

-- ---------------------------------------------------------------- idempotency
--
-- A user who refreshes the registration page, or comes back from the payment provider
-- with the back button, must not create a second partuur.
--
-- The client generates this key once per form session and sends it with every attempt;
-- the unique index turns a resend into a conflict the API can answer with the existing
-- registration rather than a duplicate. Same mechanism as client_mutation_id on match
-- results, which has already proved itself at the pitch.
alter table public.tournament_registrations
  add column if not exists idempotency_key uuid;

create unique index if not exists tournament_registrations_idempotency_key_key
  on public.tournament_registrations (idempotency_key)
  where idempotency_key is not null;

comment on column public.tournament_registrations.idempotency_key is
  'Per registration attempt, generated by the client. Makes a refresh or a return from '
  'the payment page a no-op instead of a duplicate partuur.';
